# Generated by Django 4.1.3 on 2022-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
